import dotenv from 'dotenv';
dotenv.config();

export class ExplainabilityService {
  private static instance: ExplainabilityService | null = null;
  private apiKey: string | null = null;

  private constructor() {
    this.apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || null;
    if (!this.apiKey) {
      console.warn('ExplainabilityService: GEMINI_API_KEY is missing. Mock scores will be used.');
    }
  }

  public static getInstance(): ExplainabilityService {
    if (!ExplainabilityService.instance) {
      ExplainabilityService.instance = new ExplainabilityService();
    }
    return ExplainabilityService.instance;
  }

  private async callGemini(prompt: string, useJson: boolean = false): Promise<string> {
    if (!this.apiKey) {
      throw new Error('API key not set');
    }

    const model = 'gemini-2.5-flash';
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.apiKey}`;

    const requestBody = {
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: useJson ? {
        responseMimeType: 'application/json',
      } : undefined,
    };

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini API returned HTTP ${response.status}: ${errorText}`);
      }

      const resJson = await response.json() as any;
      const text = resJson?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) {
        throw new Error('Empty response from Gemini API');
      }
      return text.trim();
    } catch (err) {
      console.error('Error calling Gemini API for explainability:', err);
      throw err;
    }
  }

  public async scoreConfidence(
    agentName: string,
    output: string,
    context: string
  ): Promise<{ confidence: number; reasoning: string; gatedForReview: boolean }> {
    if (!this.apiKey) {
      // Mock score when no API key is available
      return {
        confidence: 85,
        reasoning: 'API Key not provided. Defaulting to high confidence stub.',
        gatedForReview: false,
      };
    }

    const prompt = `
      You are an AI explainability auditor.
      Your task is to review the output generated by a legal AI agent ("${agentName}") and determine how confident the agent should be (0 to 100) based on the provided context evidence.
      If the context contains concrete evidence backing the output, the score should be high.
      If the output makes assumptions, has vague details, or lacks evidence in the context, the score should be low.

      Context provided to the agent:
      """
      ${context.slice(0, 4000)}
      """

      Agent Output:
      """
      ${output.slice(0, 4000)}
      """

      You must return a JSON object with this exact shape:
      {
        "confidence": 85,
        "reasoning": "A single sentence explaining why this score was assigned."
      }
    `;

    try {
      const responseText = await this.callGemini(prompt, true);
      const parsed = JSON.parse(responseText);
      const confidence = typeof parsed.confidence === 'number' ? parsed.confidence : 80;
      const reasoning = parsed.reasoning || 'No reasoning provided by explainability model.';
      const gatedForReview = confidence < 70;

      return {
        confidence,
        reasoning,
        gatedForReview,
      };
    } catch (err) {
      console.error('Failed to score confidence, returning fallback values:', err);
      return {
        confidence: 75,
        reasoning: 'Failed to run explainability engine. Falling back to default confidence.',
        gatedForReview: false,
      };
    }
  }
}
export default ExplainabilityService;
